// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq_FYZJPiOe43kSFm9yqZEvklyHv4lKi4',
    appId: '1:282024008875:web:8285220169c11957f22bee',
    messagingSenderId: '282024008875',
    projectId: 'flutter-book-app-9d09b',
    authDomain: 'flutter-book-app-9d09b.firebaseapp.com',
    storageBucket: 'flutter-book-app-9d09b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4f-Tr7sXmlseEaemGt-asyQ7Ui6SdNlI',
    appId: '1:282024008875:android:ad2cf8b9f8afb1a2f22bee',
    messagingSenderId: '282024008875',
    projectId: 'flutter-book-app-9d09b',
    storageBucket: 'flutter-book-app-9d09b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG1mcF_wnK_SCNDYcjHIVdGLtgEhEOGOk',
    appId: '1:282024008875:ios:1c3ce92bb4efc045f22bee',
    messagingSenderId: '282024008875',
    projectId: 'flutter-book-app-9d09b',
    storageBucket: 'flutter-book-app-9d09b.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG1mcF_wnK_SCNDYcjHIVdGLtgEhEOGOk',
    appId: '1:282024008875:ios:1c3ce92bb4efc045f22bee',
    messagingSenderId: '282024008875',
    projectId: 'flutter-book-app-9d09b',
    storageBucket: 'flutter-book-app-9d09b.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq_FYZJPiOe43kSFm9yqZEvklyHv4lKi4',
    appId: '1:282024008875:web:d8b26e25a0237f07f22bee',
    messagingSenderId: '282024008875',
    projectId: 'flutter-book-app-9d09b',
    authDomain: 'flutter-book-app-9d09b.firebaseapp.com',
    storageBucket: 'flutter-book-app-9d09b.firebasestorage.app',
  );
}
